### Data Cleaning Steps

1. Drop Remarks col
2. set index 1st col
3. Rename all col
4. Convert amount to cr rupees
5. date col
6. Drop na

In [41]:
import numpy as np
import pandas as pd

In [42]:
df = pd.read_csv("startup_funding.csv")
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3044 entries, 0 to 3043
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Sr No              3044 non-null   int64
 1   Date dd/mm/yyyy    3044 non-null   object
 2   Startup Name       3044 non-null   object
 3   Industry Vertical  2873 non-null   object
 4   SubVertical        2108 non-null   object
 5   City  Location     2864 non-null   object
 6   Investors Name     3020 non-null   object
 7   InvestmentnType    3040 non-null   object
 8   Amount in USD      2084 non-null   object
 9   Remarks            419 non-null    object
dtypes: int64(1), object(9)
memory usage: 237.9+ KB

In [43]:
import re
import unicodedata

# 1. Load file
df = pd.read_csv("startup_funding.csv")

# 2. Column containing startup/company names
name_col = "Startup Name"

# 3. Common suffixes to remove
suffixes = [
    "technologies", "technology", "tech", "labs", "lab",
    "systems", "system", "solutions", "solution",
    "services", "service", "ventures", "venture",
    "foods", "food", "retail", "mobility",
    "cabs", "cab", "app", "online", "india",
    "pvt ltd", "private limited", "privatelimited",
    "ltd", "limited", "inc", "llp", "co", "company",
    "enterprise", "enterprises", "group", "digital"
]

# Convert suffixes into compact format
suffixes_compact = sorted(
    {re.sub(r"[^a-z0-9]", "", s.lower()) for s in suffixes},
    key=len,
    reverse=True
)

def clean_text(s):
    if pd.isna(s):
        return ""
    s = str(s)

    # convert fancy apostrophes etc. to normal ASCII
    s = unicodedata.normalize("NFKD", s).encode("ascii", "ignore").decode("ascii")

    # lowercase
    s = s.lower()

    # replace & with and
    s = s.replace("&", " and ")

    # remove apostrophes
    s = re.sub(r"[\"'`’]+", "", s)

    # keep only letters and numbers
    s = re.sub(r"[^a-z0-9]+", " ", s)

    # remove extra spaces
    s = re.sub(r"\s+", " ", s).strip()

    return s

def compact_text(s):
    return re.sub(r"[^a-z0-9]", "", clean_text(s))

def root_key(s):
    s = compact_text(s)

    # remove suffixes repeatedly
    changed = True
    while changed and s:
        changed = False
        for suf in suffixes_compact:
            if len(s) > len(suf) + 2 and s.endswith(suf):
                s = s[:-len(suf)]
                changed = True
                break
    return s

# 4. Create cleaned company name
df["Startup Name"] = df[name_col].apply(root_key)
df.head()

,Sr No,Date dd/mm/yyyy,Startup Name,Industry Vertical,SubVertical,City Location,Investors Name,InvestmentnType,Amount in USD,Remarks
0,1,09/01/2020,byjus,E-Tech,E-learning,Bengaluru,Tiger Global Management,Private Equity Round,"20,00,00,000",NaN
1,2,13/01/2020,shuttl,Transportation,App based shuttle service,Gurgaon,Susquehanna Growth Equity,Series C,"80,48,394",NaN
2,3,09/01/2020,mamaearth,E-commerce,Retailer of baby and toddler products,Bengaluru,Sequoia Capital India,Series B,"1,83,58,860",NaN
3,4,02/01/2020,httpswwwwealthbucketin,FinTech,Online Investment,New Delhi,Vinod Khatumal,Pre-series A,"30,00,000",NaN
4,5,02/01/2020,fashor,Fashion and Apparel,Embroiled Clothes For Women,Mumbai,Sprout Venture Partners,Seed Round,"18,00,000",NaN

In [44]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3044 entries, 0 to 3043
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Sr No              3044 non-null   int64
 1   Date dd/mm/yyyy    3044 non-null   object
 2   Startup Name       3044 non-null   object
 3   Industry Vertical  2873 non-null   object
 4   SubVertical        2108 non-null   object
 5   City  Location     2864 non-null   object
 6   Investors Name     3020 non-null   object
 7   InvestmentnType    3040 non-null   object
 8   Amount in USD      2084 non-null   object
 9   Remarks            419 non-null    object
dtypes: int64(1), object(9)
memory usage: 237.9+ KB

In [45]:
df.columns

Index(['Sr No', 'Date dd/mm/yyyy', 'Startup Name', 'Industry Vertical',
       'SubVertical', 'City  Location', 'Investors Name', 'InvestmentnType',
       'Amount in USD', 'Remarks'],
      dtype='object')

In [46]:
sorted(df['Startup Name'].unique().tolist())

['121policy',
 '19thmile',
 '1crowd',
 '1mg',
 '1mghealthkartplus',
 '20dresses',
 '33coupons',
 '360ride',
 '3dexter',
 '3hcare',
 '3rdflix',
 '48east',
 '4tigo',
 '5thvital',
 '6degree',
 '75f',
 '91springboard',
 '99games',
 '99perhour',
 '9stacks',
 'aadharapicom',
 'aadyah',
 'aagaarcom',
 'aahaa',
 'aahaastores',
 'aandrbonvivants',
 'aaravuav',
 'aasaanjobs',
 'aashiyaan',
 'aavishkaarintellecap',
 'aberuk',
 'abhibus',
 'abihealth',
 'absentia',
 'absentiavr',
 'ace2three',
 'aceturtle',
 'acko',
 'actionableanalytics',
 'activeai',
 'actofit',
 'actonmagic',
 'ad2pro',
 'addresshealth',
 'admitkard',
 'adpushup',
 'adstringo',
 'adurcup',
 'advancedstructures',
 'advantageclub',
 'advenio',
 'adwyze',
 'adytude',
 'aeonlearning',
 'aequm',
 'aermed',
 'affimity',
 'affordplan',
 'agara',
 'agentdesks',
 'agricx',
 'agrostar',
 'agrowave',
 'ahataxis',
 'aircto',
 'airmed',
 'airpay',
 'airwood',
 'airzaar',
 'aisle',
 'akosha',
 'alefnmobi',
 'allizhealth',
 'allygrow',
 'almaconnect',
 'almamapper',
 'alphacapital',
 'alteriacapital',
 'alternacare',
 'altizone',
 'amagimedia',
 'ambee',
 'americanvision',
 'amigobulls',
 'ampere',
 'amperevehicles',
 'anakage',
 'anandakanda',
 'anchanto',
 'annapurnafinance',
 'antuit',
 'appario',
 'appbase',
 'appbrowzer',
 'appdaily',
 'appedo',
 'appie',
 'appilyever',
 'appknox',
 'applicate',
 'appliedsolar',
 'applop',
 'appsdaily',
 'appvigil',
 'appvirality',
 'arcatron',
 'arkinnet',
 'arkrobot',
 'arohanfinancial',
 'arthdesignbuild',
 'artoo',
 'aryaai',
 'aryaka',
 'asiainstituteofmedicalscience',
 'askmygift',
 'asocon',
 'atherenergy',
 'athletto',
 'atlan',
 'atomberg',
 'attune',
 'augrav',
 'autobix',
 'autogrid',
 'automationanywhere',
 'autorox',
 'autosense',
 'avagmah',
 'availfinance',
 'avantilearning',
 'avenuegrowth',
 'avishkaarbox',
 'awaazde',
 'awesummly',
 'awfis',
 'awign',
 'axio',
 'axtria',
 'ayefinance',
 'azah',
 'azuro',
 'b9beverages',
 'babajobs',
 'babyberry',
 'babychakra',
 'babygogo',
 'babyonboard',
 'badiyajobs',
 'baggout',
 'balance',
 'banihal',
 'bankbazaar',
 'bankerbay',
 'batsondelivery',
 'baxi',
 'beaconstalk',
 'beardo',
 'beatroute',
 'bedbathmore',
 'belita',
 'belong',
 'benepik',
 'bestdealfinance',
 'betaout',
 'betterbutterin',
 'bettermortgage',
 'betterplace',
 'beusalons',
 'bevy',
 'bewakoof',
 'beyondevolution',
 'bharatbazaar',
 'bharatpe',
 'bhive',
 'bhiveworkspace',
 'bibox',
 'bidgely',
 'bigbasket',
 'bigfish',
 'bigstylist',
 'bigstylistcom',
 'bikxie',
 'billdesk',
 'billionloans',
 'bira91',
 'biryaniblues',
 'biryanibykilo',
 'biteclub',
 'bitgiving',
 'bitlasoftware',
 'biz2credit',
 'bizom',
 'bizongo',
 'blackbuck',
 'blacksoil',
 'blackwhiteorange',
 'blackwhiteorangebrands',
 'blinge',
 'blogbeats',
 'bloodncare',
 'blowhorn',
 'blubox',
 'bluebirch',
 'blueboxmedia',
 'bluegape',
 'bluegapecom',
 'bluestone',
 'bluetokaicoffee',
 'boardinfinity',
 'bobble',
 'boibanit',
 'bollantindustries',
 'bolo',
 'bolrealty',
 'bombayshaving',
 'bombayshirt',
 'bonavita',
 'bonhomia',
 'bonphulapl',
 'bookeventz',
 'bookmein',
 'bookmybai',
 'bookmydiamond',
 'bookmyshow',
 'bookservicing',
 'bottrme',
 'bounty',
 'box8',
 'boxmyspace',
 'boxxai',
 'brick2wall',
 'bridgei2i',
 'brigge',
 'bristontechnomach',
 'bro4u',
 'broex',
 'broomberg',
 'browntape',
 'browserstack',
 'bucker',
 'buddy',
 'buddy4studdy',
 'bueno',
 'buildkar',
 'buildsupply',
 'buildtraders',
 'buildzar',
 'bumper',
 'burgersingh',
 'buttercups',
 'butterflyinteractive',
 'buyhatke',
 'byg',
 'byjus',
 'byjuxe2x80x99s',
 'cabsguru',
 'cakartin',
 'callhealth',
 'campusdiaries',
 'canvasflip',
 'canvera',
 'canvs',
 'capabiliti',
 'capillary',
 'capitalfloat',
 'capitaworld',
 'capricoast',
 'capzest',
 'caratlanecom',
 'caravancraft',
 'carcrewin',
 'cardekho',
 'cardekhocom',
 'care24',
 'career360',
 'careeranna',
 'careongo',
 'carlxe2x80x99sjr',
 'carpm',
 'cars24',
 'cartisan',
 'cartrade',
 'cartradecom',
 'carveniche',
 'casa2inns',
 'cashe',
 'cashflo',
 'cashfree',
 'cashify',
 'cashkaro',
 'cashkarocom',
 'cashkumar',
 'cashsuvidha',
 'cbrex',
 'cbs',
 'ccavenue',
 'celerix',
 'celescare',
 'cerebroz',
 'chaayos',
 'chaipoint',
 'chaithela',
 'chakrinnovation',
 'changermints',
 'chargebee',
 'chargein',
 'chatongo',
 'cheersoye',
 'chefsbasket',
 'chevon',
 'chikoop',
 'chillr',
 'chippersage',
 'chloroplast',
 'chqbook',
 'chrysalis',
 'chumbak',
 'chymeravr',
 'cimplyfive',
 'citruspayment',
 'cityflo',
 'cityfurnish',
 'cityshor',
 'civilsdaily',
 'clapsnslaps',
 'cleansecar',
 'cleartax',
 'cleartrip',
 'cleversharks',
 'clevertap',
 'click2clinic',
 'clip',
 'clodura',
 'clonect',
 'cloudacar',
 'cloudcherryanalytics',
 'cloudlending',
 'cloudrino',
 'clovia',
 'clumio',
 'codemojo',
 'coding',
 'cointribe',
 'colife',
 'collatebox',
 'collateralmedical',
 'collectabillia',
 'collegedekho',
 'collegedunia',
 'collpoll',
 'comarete',
 'commeasure',
 'commonfloor',
 'commut',
 'confirmtkt',
 'confirmttkt',
 'connaizen',
 'connect',
 'connectabank',
 'consuremedical',
 'convegenius',
 'cooey',
 'cookaroo',
 'cookifi',
 'coolshare',
 'coppre',
 'corporate360',
 'corse',
 'couponmachinein',
 'couponraja',
 'coutloot',
 'coveiot',
 'coverfox',
 'craftstvilla',
 'craftsvilla',
 'crayondata',
 'creatorxe2x80x99sgurukul',
 'credifiable',
 'credihealth',
 'creditmantri',
 'creditmate',
 'creditseva',
 'creditsudhaar',
 'creditvidya',
 'credr',
 'credright',
 'credy',
 'creo',
 'crofarm',
 'cron',
 'cropin',
 'crossahead',
 'crowdera',
 'crowdfireformerlyjustunfollow',
 'crownit',
 'cube26',
 'cubeconsumer',
 'cuberoot',
 'cubito',
 'cuelearn',
 'cuemath',
 'cult',
 'cultfitness',
 'culturealley',
 'culturemachine',
 'cupick',
 'cuponation',
 'curatio',
 'curefit',
 'cureinstant',
 'curejoy',
 'curie',
 'curiositi',
 'curofy',
 'customer360',
 'customersucessbox',
 'customfurnish',
 'customfurnishcom',
 'cyclops',
 'cyclopsmed',
 'cygnushospitals',
 'daaki',
 'daalchini',
 'dailyhunt',
 'dailyninja',
 'dailyobjects',
 'dailyrounds',
 'darwinbox',
 'dataresolve',
 'dataweave',
 'dawailelo',
 'daybox',
 'dazo',
 'deal4loans',
 'deal4loanswishfin',
 'dealstreetasia',
 'dealwithus',
 'degustibus',
 'dekkho',
 'delhivery',
 'delight',
 'demyto',
 'derbii',
 'designbids',
 'designcafe',
 'devourin',
 'deyorcamps',
 'deyorrooms',
 'dhruva',
 'dhruvaspace',
 'diabetomics',
 'didi',
 'digiconectt',
 'digilend',
 'digio',
 'digit',
 'digitalf5',
 'digitalgorkha',
 'digitalmallasia',
 'dilmil',
 'dipper',
 'directcreate',
 'diro',
 'dish',
 'dishq',
 'disprz',
 'djubocom',
 'docplexus',
 'docs',
 'doctalk',
 'doctorinsta',
 'dogspot',
 'donething',
 'donxe2x80x99tscratchyourhead',
 'doodhwala',
 'doormint',
 'doselect',
 'doxper',
 'dream11',
 'dreamwallets',
 'dripcapital',
 'driverscart',
 'driveskool',
 'drivestream',
 'driveu',
 'drivezy',
 'drivify',
 'drivojoy',
 'droom',
 'droomin',
 'dropkaffe',
 'drums',
 'druva',
 'duffl',
 'dunzo',
 'earlysalary',
 'earlysalarycom',
 'earth',
 'easydiner',
 'easyecom',
 'easyfix',
 'easygov',
 'easykhaana',
 'easypolicy',
 'easyrewardz',
 'easyroads',
 'eatfresh',
 'eatlo',
 'eatonomist',
 'eatshoplove',
 'eattreat',
 'eazycoach',
 'eazydiner',
 'ebikego',
 'eckovation',
 'ecolibriumenergy',
 'ecomexpress',
 'ecozen',
 'edelweiss',
 'edgefx',
 'edtechreview',
 'edu4share',
 'eduace',
 'edubridge',
 'edukart',
 'edupristine',
 'edureka',
 'edurev',
 'edyoo',
 'ekincare',
 'elanic',
 'elasticrun',
 'elastirun',
 'elderaidwellness',
 'elemential',
 'elong',
 'elucidata',
 'emfluxmotors',
 'emiza',
 'emojifi',
 'enabli',
 'enakshi',
 'encashea',
 'endlessrobotics',
 'engineerai',
 'engineerbabu',
 'englishleapcom',
 'enkast',
 'entropik',
 'entropika',
 'entropyinnovations',
 'envoged',
 'epathsala',
 'epaylater',
 'epiqcapital',
 'epoise',
 'eps',
 'equickies',
 'era',
 'eruditus',
 'esadar',
 'esahaiin',
 'eshakti',
 'eshiksha',
 'eswasthya',
 'etaout',
 'ethinos',
 'ethosh',
 'eureqa',
 'evengini',
 'eveningflavors',
 'eventshigh',
 'evibein',
 'explara',
 'explorelifetraveling',
 'extraaedge',
 'extracarbon',
 'eywamedia',
 'ezcred',
 'ezetap',
 'ezyhaul',
 'ezysolare',
 'ezytruk',
 'faasos',
 'faasoxe2x80x99s',
 'faaya',
 'faballey',
 'fabhotels',
 'fablestreet',
 'fabogo',
 'fabulyst',
 'fabx',
 'faircent',
 'faircentcom',
 'falconbrick',
 'fame',
 'fareye',
 'farmart',
 'farmizen',
 'farmlink',
 'farmtaaza',
 'fashalot',
 'fashionablyin',
 'fashionove',
 'fashor',
 'fastfox',
 'fastudent',
 'feetapart',
 'fieldassist',
 'financebuddha',
 'fincash',
 'findmeashoe',
 'findmystay',
 'findow',
 'findurclass',
 'findyahan',
 'fingerlix',
 'finomena',
 'finovacapital',
 'fintellix',
 'fintobox',
 'finzy',
 'firstcry',
 'firstcrycom',
 'firsteat',
 'firstmomsclub',
 'firsttouch',
 'fisdom',
 'fitcircle',
 'fitmein',
 'fitn',
 'fitpass',
 'fitraq',
 'fitraqcom',
 'fitso',
 'fitternity',
 'fivestar',
 'fixnix',
 'fixy',
 'flashdoor',
 'flatchat',
 'flatfurnish',
 'flatpebble',
 'fleetrover',
 'fleetx',
 'flexiloans',
 'flexingit',
 'flickbay',
 'flickstree',
 'flipclass',
 'flipkart',
 'flipkartcom',
 'flixygames',
 'flocareer',
 'flochat',
 'flutura',
 'flyrobe',
 'flytxt',
 'focusdigit',
 'foodabhi',
 'foodmemories',
 'foodpanda',
 'foodtalk',
 'forevershop',
 'formcept',
 'fourseven',
 'fourthambit',
 'fourthpartnerenergy',
 'foyrcom',
 'fpl',
 'fr8',
 'fracktalworks',
 'fractalanalytics',
 'frankly',
 'frapperz',
 'freecharge',
 'freedomsmart',
 'freshboxx',
 'freshdesk',
 'freshee',
 'freshfoodconcepts',
 'freshmenu',
 'freshmonk',
 'freshvnf',
 'freshworks',
 'freshworld',
 'frontdeskai',
 'froyofit',
 'frsh',
 'frshcoin',
 'ftcash',
 'fulfilio',
 'funcart',
 'funcastic',
 'fundamentor',
 'fundsindiacom',
 'funongo',
 'furdo',
 'furlen',
 'furtadosschoolofmusic',
 'fusionmicrofinance',
 'fxkartcom',
 'fxmart',
 'fyle',
 'fynd',
 'fyne',
 'fyre',
 'gaana',
 'gaanacom',
 'gadgets360',
 'gadgetwood',
 'gajty',
 'galleri5',
 'gameezop',
 'gamexsin',
 'gamezop',
 'gamingmonk',
 'gamooz',
 'gapoon',
 'garageonroad',
 'gear6',
 'genextstudents',
 'genie',
 'geniuscorner',
 'gennextstudents',
 'getfocus',
 'getmyparking',
 'getmypeon',
 'getnow',
 'getsimpl',
 'getvee',
 'gibbs',
 'gibss',
 'giftxoxo',
 'gig',
 'gingercrush',
 'girnarsoftware',
 'glamrs',
 'glamstudios',
 'glassic',
 'glowroad',
 'glowship',
 'goalwise',
 'gobolt',
 'gobumpr',
 'gochoppers',
 'gocomet',
 'godesi',
 'godofhospitals',
 'gofro',
 'gofynd',
 'gogotruck',
 'gojavas',
 'goldfarm',
 'golflan',
 'gomalon',
 'gomechanic',
 'good',
 'goodbox',
 'goodera',
 'goodmethodsglobal',
 'goomo',
 'gopigeon',
 'goqii',
 'gosporto',
 'goyano',
 'gozefo',
 'gozoomo',
 'grab',
 'grabhouse',
 'grabhousecom',
 'grabin',
 'grabonrent',
 'gradopedia',
 'gramcover',
 'gramophone',
 'grandopinion',
 'graphene',
 'graphic',
 'grayroutes',
 'greenlightplanet',
 'grex',
 'greyatom',
 'greycampus',
 'greyorange',
 'greythr',
 'gridle',
 'grofers',
 'groupon',
 'groverzampa',
 'growfit',
 'growfitter',
 'groww',
 'guarented',
 'guiddoo',
 'guidoo',
 'guruglearning',
 'gurukul',
 'gyaanzone',
 'gyandhan',
 'gympik',
 'gympikcom',
 'gymtrekker',
 'hackerearth',
 'hackerrank',
 'halaplay',
 'handyhome',
 'handytrain',
 'hansacustomerequity',
 'hanselio',
 'happay',
 'happilyunmarried',
 'happitoo',
 'happy2refer',
 'happydemic',
 'happyemi',
 'happygoeasy',
 'haptik',
 'haqdarshak',
 'harnesshanditouch',
 'hashlearn',
 'hashtaag',
 'hasura',
 'headout',
 'headsupfortails',
 'healersathome',
 'healinstitute',
 'healthassure',
 'healthbuds',
 'healthcare',
 'healthcareathome',
 'healtheminds',
 'healthenablr',
 'healthfin',
 'healthi',
 'healthians',
 'healthianscom',
 'healthifyme',
 'healthintel',
 'healthkart',
 'healthkumbh',
 'healthmir',
 'healthsignz',
 'healthsutra',
 'healthyworldin',
 'heckyl',
 'hellocurry',
 'hellotax',
 'helpchat',
 'helpi',
 'helpshift',
 'heterogenous',
 'hevodata',
 'heybiz',
 'heypillow',
 'highradius',
 'highwaydelite',
 'hijinny',
 'hike',
 'hikemessenger',
 'hipbar',
 'hipcask',
 'hipcouch',
 'hippily',
 'hipship',
 'hitgrit',
 'hitwicket',
 'holachef',
 'holidayiq',
 'holidify',
 'holisollogistics',
 'homecapital',
 'homelane',
 'homergize',
 'homersin',
 'homestudio',
 'hoopy',
 'hoppingchef',
 'hoppingo',
 'hopscotch',
 'horntell',
 'hosteldunia',
 'hotelogix',
 'hotify',
 'housejoy',
 'houseofmsasaba',
 'housing',
 'housingcom',
 'housingman',
 'houssup',
 'howdy',
 'httpswwwwealthbucketin',
 'hubilo',
 'hugefly',
 'huginnovations',
 'hungama',
 'hungerbox',
 'hungryfoal',
 'hwell24',
 'hwell24plus',
 'hypernovainteractive',
 'hypertrack',
 'hyperverge',
 'i2e1',
 'i2ifunding',
 'i3sysytems',
 'iamwire',
 'iaugmentor',
 'ibsfin',
 'ibusnetworks',
 'icanstay',
 'icertis',
 'ichefin',
 'ichr',
 'icliniq',
 'icrushiflush',
 'icustomadeit',
 'icustommadeit',
 'ideabubbles',
 'ideachakki',
 'ideaforge',
 'idealinsurance',
 'idfy',
 'idg',
 'idreamcareer',
 'ifmrholdings',
 'igenetics',
 'igniscareers',
 'igpcom',
 'igrenenergi',
 'iimjobs',
 'ilend',
 'imageprovision',
 'imaginate',
 'imanagemyhotel',
 'imarticuslearning',
 'imaxprogram',
 'imbesharam',
 'imedilane',
 'immilife',
 'impactanalytics',
 'impactguru',
 'impartus',
 'inayo',
 'inc42',
 'inclov',
 'incred',
 'incredfinance',
 'increff',
 'indee',
 'indiagiftsportal',
 'indialends',
 'indiamart',
 'indianrootscom',
 'indicom',
 'indiez',
 'indifi',
 'indigolearn',
 'indix',
 'indofash',
 'indusos',
 'industrybuying',
 'indwealth',
 'infeedo',
 'infibeam',
 'infiniteanalytics',
 'infisecure',
 'infogain',
 'infoworks',
 'infurnia',
 'inicu',
 'inkmonk',
 'inmobi',
 'inmotion',
 'innefusecurityconsulting',
 'innerchef',
 'innerhour',
 'innonanoresearch',
 'innoplexus',
 'innov8',
 'innovaccer',
 'innovapptive',
 'innoviti',
 'inshorts',
 'insiderin',
 'inspirock',
 'instabounce',
 'instacar',
 'instalively',
 'instalivelycom',
 'instantpay',
 'instaoffice',
 'instaproc',
 'instasafe',
 'instavans',
 'intelligencenode',
 'intelligentinterfaces',
 'interviewpad',
 'intgrea',
 'inthree',
 ...]

In [47]:


usd_to_inr = 83.0

def usd_to_crore_rupees(x):
    if pd.isna(x):
        return np.nan

    s = str(x).strip().lower()
    s = s.replace("\u00a0", " ").replace("\xa0", " ")
    s = re.sub(r"(\\\\xc2\\\\xa0|\\xc2\\xa0)", " ", s)

    if s in {"", "nan", "none", "n/a", "na", "unknown", "undisclosed"}:
        return np.nan

    s = re.sub(r"[^0-9.,+]", "", s)
    s = s.replace("+", "")
    s = s.replace(",", "")

    try:
        usd = float(s)
        return round((usd * usd_to_inr) / 10000000, 2)
    except:
        return np.nan

df["Amount in USD"] = df["Amount in USD"].apply(usd_to_crore_rupees)

#print(df[["Amount in USD", "Amount in INR Cr"]].head(20))

#df.drop("Amount in USD",axis=1,inplace = True)

In [ ]:

df.drop("Remarks", axis=1, inplace=True)

In [51]:
df.rename(columns={"Amount in USD": "Amount in INR Cr"}, inplace=True)
df.head(5)

,Sr No,Date dd/mm/yyyy,Startup Name,Industry Vertical,SubVertical,City Location,Investors Name,InvestmentnType,Amount in INR Cr
0,1,09/01/2020,byjus,E-Tech,E-learning,Bengaluru,Tiger Global Management,Private Equity Round,1660.00
1,2,13/01/2020,shuttl,Transportation,App based shuttle service,Gurgaon,Susquehanna Growth Equity,Series C,66.80
2,3,09/01/2020,mamaearth,E-commerce,Retailer of baby and toddler products,Bengaluru,Sequoia Capital India,Series B,152.38
3,4,02/01/2020,httpswwwwealthbucketin,FinTech,Online Investment,New Delhi,Vinod Khatumal,Pre-series A,24.90
4,5,02/01/2020,fashor,Fashion and Apparel,Embroiled Clothes For Women,Mumbai,Sprout Venture Partners,Seed Round,14.94

In [52]:
df.set_index('Sr No',inplace = True )

In [67]:
df.columns

Index(['Date', 'Startup', 'vertical', 'subvertical', 'city', 'investors',
       'round', 'amount'],
      dtype='object')

In [64]:
df.rename(columns ={
     'Date dd/mm/yyyy' : 'date',
    'Startup Name' : 'Startup',
    'Industry Vertical' :'vertical',
    'SubVertical' : 'subvertical',
    'City  Location' : 'city',
    'Investors Name' : 'investors',
    'InvestmentnType' : 'round',
    'Amount in INR Cr' : 'amount'    
    
},inplace = True)

In [57]:
df['amount'] = df['amount'].fillna(0)
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3044 entries, 1 to 3044
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Date         3044 non-null   object
 1   Startup      3044 non-null   object
 2   vertical     2873 non-null   object
 3   subvertical  2108 non-null   object
 4   city         2864 non-null   object
 5   investors    3020 non-null   object
 6   round        3040 non-null   object
 7   amount       3044 non-null   float64
dtypes: float64(1), object(7)
memory usage: 214.0+ KB

In [ ]:
## Date column is object type. We need to convert it to datetime type for better analysis. Let's do that.
df['Date'] = pd.to_datetime(df['Date'], format='%d/%m/%Y')

In [68]:
df["Date"] = pd.to_datetime(
    df["Date"],
    format="%d/%m/%Y",
    errors="coerce"
)